<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sDr. Who, The Musical!%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Lorem ipsum dolor sit amet..')) ?></p>
    <p class="text-center"><a class="btn btn-success btn-lg" href="registrant/add"><?php echo $this->translate('Sign Up for Tickets') ?> </a></p>
</div>

<div class="row">

</div>
